permalink:           Cortexiphan
title:               Cortexiphan - Cursos
tagline:             Essa p치gina foi dessenvolvida com o intuito de juntas o m치ximo de cursos em uma s칩 p치gina.
url:                 http://andreyglauzer.github.io
baseurl:             /cortexiphan
owner:
  name:           Cortexiphan
version:             2.0.0
github:
  repo:              
